spring.application.name=DevLens


# Server Settings
server.port=${SERVER_PORT}
spring.main.web-application-type=${SPRING_MAIN_WEB_APPLICATION_TYPE}
spring.main.banner-mode=${SPRING_MAIN_BANNER_MODE}

