spring:
  application:
    name: DevLens
  config:
    import: "optional:file:.env[.properties]"
  main:
    web-application-type: ${SPRING_MAIN_WEB_APPLICATION_TYPE}
    banner-mode: ${SPRING_MAIN_BANNER_MODE}
  datasource:
    driver-class-name: ${SPRING_DATASOURCE_DRIVER_CLASS_NAME}
    url: ${SPRING_DATASOURCE_URL}
    username: ${SPRING_DATASOURCE_USERNAME}
    password: ${SPRING_DATASOURCE_PASSWORD}
  jpa:
    hibernate:
      ddl-auto: ${SPRING_JPA_HIBERNATE_DDL_AUTO}
    generate-ddl: ${SPRING_JPA_GENERATE_DDL}
    show-sql: ${SPRING_JPA_SHOW_SQL}
    properties:
      hibernate:
        format_sql: ${SPRING_JPA_PROPERTIES_HIBERNATE_FORMAT_SQL}
    database-platform: ${SPRING_JPA_DATABASE_PLATFORM}

server:
  port: ${SERVER_PORT}